apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: emqx
  labels:
    app: emqx
data:
  EMQX_NODE_NAME: "emqx@emqx-0.emqx-headless.emqx.svc.cluster.local"
  EMQX_ALLOW_ANONYMOUS: "true"
