apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emqx

labels:
  - pairs:
      app: emqx
    includeSelectors: true

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - emqx-statefulset.yaml
  - emqx-service.yaml
