apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
  namespace: emqx
  labels:
    app: emqx
type: Opaque
stringData:
  EMQX_DASHBOARD__DEFAULT_USERNAME: admin
  EMQX_DASHBOARD__DEFAULT_PASSWORD: changeme_emqx_2024
